modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="testing"
version="1.0.0"
displayName="Testing"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="brook, MCreator"

[[dependencies.testing]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




